# Generated by Django 4.0.4 on 2022-05-01 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0006_alter_task_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='user',
        ),
    ]
