# Generated by Django 4.0.4 on 2022-05-04 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0010_alter_task_task_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='task_id',
            new_name='key',
        ),
    ]
